name: "20 CD Pipeline"
on:
  workflow_dispatch:
    inputs:
      ci_run_id:
        description: "Run ID of the CI pipeline run to reference the Docker image and Terraform artifacts."
        required: true

jobs:
  test:
    runs-on: ubuntu-24.04
    # if: false # Temporarely disabling this job to work on something else instead
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Use custom Terraform provision action"
        uses: ./.github/actions/terraform-provision
        with:
          tf_api_token: ${{ secrets.TF_API_TOKEN }}
          workspace: test
          varfile: "values/test.tfvars"
          docker_image: ${{ vars.DOCKER_HUB_USERNAME }}/juice-shop:${{ github.event.inputs.ci_run_id }}

  prod:
    runs-on: ubuntu-24.04
    needs: test
    # if: false # Temporarely disabling this job to work on something else instead
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Use custom Terraform provision action"
        uses: ./.github/actions/terraform-provision
        with:
          tf_api_token: ${{ secrets.TF_API_TOKEN }}
          workspace: prod
          varfile: "values/prod.tfvars"
          docker_image: ${{ vars.DOCKER_HUB_USERNAME }}/juice-shop:${{ github.event.inputs.ci_run_id }}
