name: "20 CD Pipeline"
on:
  workflow_dispatch:
    inputs:
      dockerImageTag:
        description: "Docker image tag to deploy"
        required: true


env:
  TF_HOME: ${{ github.workspace }}/terraform

jobs:
  dev:
    runs-on: ubuntu-24.04
    # if: false # Temporarely disabling this job to work on something else instead
    env:
      TF_WORKSPACE: test # This hardcodes the Terraform workspace to be used

      # Below value will be picked up by the Terraform script
      TF_VAR_docker_image: ${{ vars.DOCKER_HUB_USERNAME }}/juice-shop:${{ github.event.inputs.dockerImageTag }}
    steps:
      - name: "Use custom Terraform provision action"
        uses: ./.github/actions/terraform-provision
        with:
          varfile: "values/test.tfvars"

  prod:
    needs: dev
    runs-on: ubuntu-24.04
    # if: false # Temporarely disabling this job to work on something else instead
    env:
      TF_WORKSPACE: prod # This hardcodes the Terraform workspace to be used

      # Below value will be picked up by the Terraform script
      TF_VAR_docker_image: ${{ vars.DOCKER_HUB_USERNAME }}/juice-shop:${{ github.event.inputs.dockerImageTag }}
    steps:
      - name: "Use custom Terraform provision action"
        uses: ./.github/actions/terraform-provision
        with:
          varfile: "values/prod.tfvars"
