name: "20 CD Pipeline"
on:
  # TODO manual workflow dispatch requires additional configuration
  # workflow_dispatch:  # Allows manual triggering of the workflow
  workflow_run:
    workflows: ["10 CI Pipeline"] # Run CD pipeline after CI is successful
    types:
      - completed

jobs:
  dev:
    runs-on: ubuntu-24.04
    # if: false # Temporarely disabling this job to work on something else instead
    env:
      TF_WORKSPACE: test

      # Below value will be picked up by the Terraform script
      TF_VAR_docker_image: ${{ vars.DOCKER_HUB_USERNAME }}/juice-shop:12419828744 # TODO Put this back once the CD pipeline overall works ${{ github.run_id }}
    steps:
      - name: "Download CI Terraform artifacts"
        uses: actions/download-artifact@v4
        with:
          name: terraform

      - name: "Install Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: "Terraform Provision Resources"
        run: |
          cd $GITHUB_WORKSPACE/terraform
          terraform workspace select $TF_WORKSPACE
          terraform init
          terraform apply -auto-approve
          cd -

  prod:
    needs: dev
    runs-on: ubuntu-24.04
    # if: false # Temporarely disabling this job to work on something else instead
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Deploy to Prod"
        run: echo "Deploying to Prod environment"