name: "CI Pipeline"
on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@v4.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=basiuktv
            -Dsonar.projectKey=BasiukTV_devsecops-sandbox-juice-shop

  docker:
    runs-on: ubuntu-24.04
    env:
      DOCKER_HUB_USERNAME: tbeit
    if: false # Temporarely disabling this job to work on something else instead
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Login to Docker Hub"
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ env.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: "Build Docker image"
        run: docker build -t ${{ env.DOCKER_HUB_USERNAME }}/juice-shop:${{ github.run_id }} .

      - name: "Start Workflow Summary"
        run: echo '## Docker Scout Scan Results' >> $GITHUB_STEP_SUMMARY

      - name: Docker Scout Scan
        uses: docker/scout-action@v1.16.1
        with:
          command: quickview,cves,recommendations
          only-severities: critical,high
          # exit-code: true # Fails the whole job if the vulnerabilities are found

      - name: "Push Docker image"
        run: docker push ${{ env.DOCKER_HUB_USERNAME }}/juice-shop:${{ github.run_id }}
